name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagesTemp/кавказ.jpg
    - assets/imagesTemp/Питер.jpg
    - assets/imagesTemp/Химки.jpg
